### ISSUE TITLE
Update package testing

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#1016]
## Issue Description
- [x] Migrate unittests to GitHub Actions (run per commit),  Run piwind checks on a per PR basis 
- [x] Setup test Matrix of requirement versions 

Mismatches with `numpy` and `numba` version requirements can create problems installing oasislmf. 

Add additional stages to CI which installs the source package across multiple python versions. 

**Example Error** 
```
Building wheels for collected packages: oasislmf
  Building wheel for oasislmf (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/mtazzari/envs/tests_py38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-enn8y51b/oasislmf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-enn8y51b/oasislmf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-z8xk4tgj
       cwd: /tmp/pip-install-enn8y51b/oasislmf/
  Complete output (17 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-enn8y51b/oasislmf/setup.py", line 334, in <module>
      setup(
    File "/home/mtazzari/envs/tests_py38/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 134, in setup
      ok = dist.parse_command_line()
    File "/home/mtazzari/envs/tests_py38/lib/python3.8/site-packages/setuptools/dist.py", line 707, in parse_command_line
      result = _Distribution.parse_command_line(self)
    File "/usr/lib/python3.8/distutils/dist.py", line 483, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/home/mtazzari/envs/tests_py38/lib/python3.8/site-packages/setuptools/dist.py", line 1014, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/usr/lib/python3.8/distutils/dist.py", line 545, in _parse_command_opts
      if not issubclass(cmd_class, Command):
  TypeError: issubclass() arg 1 must be a class
  ----------------------------------------
  ERROR: Failed building wheel for oasislmf
  Running setup.py clean for oasislmf
Failed to build oasislmf
ERROR: numba 0.55.1 has requirement numpy<1.22,>=1.18, but you'll have numpy 1.22.3 which is incompatible.
```

**Comment by sambles** [comment]
Note: Add option to tests on multiple python env versions on release

**Comment by sambles** [comment]
Comment added to issue for later

> **Marco Tazzari:** I'm fine with the loose requirement. I just want to point out that on 26 may numba v0.55.2 was released and I personally haven't tested it. If we have CI tests that try that version and pass, then fine I'd go with the loose requirement. If not, I think it is risky (because untested) to allow installers to dynamically pick numba version. Numba is still experimental and can give surprises. 

> I understand that numpy 1.22 solves security issues and would be better to use it. I think the general robust solution would be to have a matrix of CI test that check builds with pinned versions of numba 0.55.1, 0.55.2, etc. In the meanwhile, if somebody can run the tests and check piwind with 0.55.2 would give us some safety in doing the release with the loose requirement.
