### ISSUE TITLE
Gulpy failing in distributed runs 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#1066]
## Issue Description
When running a higher number of loss chunks (tested using 200), gulpy can intermittently fail with `ValueError: need at least one array to concatenate`
This happens when running either **[getmodel + gulpy]** or **[modelpy + gulpy]** so the error doesn't appear to be linked with modelpy. 

```
KTOOLS_STDERR:                                                                                                      
Traceback (most recent call last):                                                                                  
  File "/home/worker/.local/bin/gulpy", line 8, in <module>                                                         
    sys.exit(main())                                                                                                
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/pytools/gulpy.py", line 47, in main               
    manager.run(**kwargs)                                                                                           
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/pytools/gul/manager.py", line 215, in run         
    for event_data in read_getmodel_stream(streams_in, item_map, coverages, compute, seeds):                        
  File "/home/worker/.local/lib/python3.10/site-packages/oasislmf/pytools/gul/io.py", line 107, in read_getmodel_str
eam                                                                                                                 
    yield last_event_id, compute_i, items_data, np.concatenate(recs), rec_idx_ptr, rng_index                        
  File "<__array_function__ internals>", line 5, in concatenate                                                     
ValueError: need at least one array to concatenate     
```

### PiWind logs
[Chunk3-Error_gulpy.log](https://github.com/OasisLMF/OasisLMF/files/9047027/Chunk3-Error_gulpy.log)
[Chunk3-working_gulcalc.log](https://github.com/OasisLMF/OasisLMF/files/9047036/Chunk3-working_gulcalc.log)

**Comment by sstruzik** [comment]
Can be reproduce locally by running:
eve 4 200 | modelpy | gulpy -S10 -L0 -a1 --logging-level 10 > gul.bin
