### ISSUE TITLE
Arg parsing error in 1.2.1

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#115]
From the Zurich workshop repo:
```
oasislmf model generate-oasis-files \
    -o "oasis_files" \
    -k "keys_data/MEEQ" \
    -v "keys_data/MEEQ/ModelVersion.csv" \
    -p "catrisks-meeq-canonical-loc-profile.json" \
    -e "source_data/MEEQ_loc.csv" \
    -b "transformation_files/MappingMapToCatrisks_CanLoc_A.xslt" \
    -d "transformation_files/MappingMapToCatrisks_ModelLoc.xslt"
```

Error trace:
```
Found canonical exposures profile: {'ROW_ID': {'ProfileElementName': 'ROW_ID', 'FieldName': 'LocationID'}, 'ACCNTNUM': {'ProfileElementName': 'ACCNTNUM', 'FieldName': 'AccountNumber'}, 'LOCNUM': {}, 'LATITUDE': {}, 'LONGITUDE': {}, 'POSTALCODE': {}, 'ADDRMATCH': {}, 'STATE': {}, 'STATECODE': {}, 'COUNTY': {}, 'COUNTYCODE': {}, 'CITY': {}, 'CITYCODE': {}, 'COUNTRY': {}, 'CNTRYSCHEME': {}, 'CNTRYCODE': {}, 'BLDGSCHEME': {}, 'BLDGCLASS': {}, 'OCCSCHEME': {}, 'OCCTYPE': {}, 'NUMBLDGS': {}, 'EQCV1VAL': {'ProfileElementName': 'EQCV1VAL', 'FieldName': 'TIV', 'PerilID': 3, 'CoverageTypeID': 1, 'FMLevelName': 'Coverage', 'FMLevel': 1, 'FMTermType': 'TIV', 'FMTermGroupID': 1, 'ProfileType': 'Loc'}, 'EQCV1VCUR': {}, 'EQCV1DED': {'ProfileElementName': 'EQCV1DED', 'FieldName': 'CoverageDeductible', 'PerilID': 3, 'CoverageTypeID': 1, 'FMLevelName': 'Coverage', 'FMLevel': 1, 'FMTermType': 'Deductible', 'FMTermGroupID': 1, 'ProfileType': 'Loc'}, 'EQCV1DCUR': {}, 'EQCV1LIMIT': {'ProfileElementName': 'EQCV1LIMIT', 'FieldName': 'CoverageLimit', 'PerilID': 3, 'CoverageTypeID': 1, 'FMLevelName': 'Coverage', 'FMLevel': 1, 'FMTermType': 'Limit', 'FMTermGroupID': 1, 'ProfileType': 'Loc'}, 'EQCV1LCUR': {}, 'EQCV2VAL': {'ProfileElementName': 'EQCV2VAL', 'FieldName': 'TIV', 'PerilID': 3, 'CoverageTypeID': 3, 'FMLevelName': 'Coverage', 'FMLevel': 1, 'FMTermType': 'TIV', 'FMTermGroupID': 2, 'ProfileType': 'Loc'}, 'EQCV2VCUR': {}, 'EQCV2DED': {'ProfileElementName': 'EQCV2DED', 'FieldName': 'CoverageDeductible', 'PerilID': 3, 'CoverageTypeID': 3, 'FMLevelName': 'Coverage', 'FMLevel': 1, 'FMTermType': 'Deductible', 'FMTermGroupID': 2, 'ProfileType': 'Loc'}, 'EQCV2DCUR': {}, 'EQCV2LIMIT': {'ProfileElementName': 'EQCV2LIMIT', 'FieldName': 'CoverageLimit', 'PerilID': 3, 'CoverageTypeID': 3, 'FMLevelName': 'Coverage', 'FMLevel': 1, 'FMTermType': 'Limit', 'FMTermGroupID': 2, 'ProfileType': 'Loc'}, 'EQCV2LCUR': {}, 'EQSITELIM': {'ProfileElementName': 'EQSITELIM', 'FieldName': 'SiteLimit', 'FMLevelName': 'Site', 'FMLevel': 3, 'FMTermType': 'Limit', 'FMTermGroupID': 1, 'ProfileType': 'Loc'}, 'EQSITELCUR': {}, 'EQSITEDED': {'ProfileElementName': 'EQSITEDED', 'FieldName': 'SiteDeductible', 'FMLevelName': 'Site', 'FMLevel': 3, 'FMTermType': 'Deductible', 'FMTermGroupID': 1, 'ProfileType': 'Loc'}, 'EQSITEDCUR': {}, 'EQCOMBINEDLIM': {'ProfileElementName': 'EQCOMBINEDLIM', 'FieldName': 'CombinedLimit', 'FMLevelName': 'Combined', 'FMLevel': 2, 'FMTermType': 'Limit', 'FMTermGroupID': 1, 'ProfileType': 'Loc'}, 'EQCOMBINEDLCUR': {}, 'EQCOMBINEDDED': {'ProfileElementName': 'EQCOMBINEDDED', 'FieldName': 'CombinedDeductible', 'FMLevelName': 'Combined', 'FMLevel': 2, 'FMTermType': 'Deductible', 'FMTermGroupID': 1, 'ProfileType': 'Loc'}, 'EQCOMBINEDDCUR': {}, 'COND1TYPE': {}, 'COND1NAME': {'ProfileElementName': 'COND1NAME', 'FieldName': 'SubLimitReference'}, 'COND1DEDUCTIBLE': {'ProfileElementName': 'COND1DEDUCTIBLE', 'FieldName': 'SubLimitDeductible'}, 'COND1LIMIT': {'ProfileElementName': 'COND1LIMIT', 'FieldName': 'SubLimitLimit', 'FMLevelName': 'Sublimit', 'FMLevel': 4, 'FMTermType': 'Limit', 'FMTermGroupID': 1, 'ProfileType': 'Loc'}}

Writing canonical exposures file /home/sam/repos/support/ZurichWorkshop2018/oasis_files/canexp-20181122121235.csv

Writing model exposures file /home/sam/repos/support/ZurichWorkshop2018/oasis_files/modexp-20181122121235.csv
Traceback (most recent call last):
  File "/home/sam/repos/core/env/py3/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/oasislmf/cmd/root.py", line 36, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/oasislmf/cmd/model.py", line 621, in action
    logger=self.logger
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/oasislmf/exposures/manager.py", line 1662, in start_oasis_files_pipeline
    self.transform_canonical_to_model(oasis_model=oasis_model, **kwargs)
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/oasislmf/exposures/manager.py", line 534, in transform_canonical_to_model
    translator = Translator(input_file_path, output_file_path, transformation_file_path, xsd_path=validation_file_path, append_row_nums=False)
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/oasislmf/exposures/csv_trans.py", line 51, in __init__
    self.xsd = (etree.parse(xsd_path) if xsd_path else None)
  File "src/lxml/etree.pyx", line 3444, in lxml.etree.parse (src/lxml/etree.c:83185)
  File "src/lxml/parser.pxi", line 1834, in lxml.etree._parseDocument (src/lxml/etree.c:120757)
  File "src/lxml/parser.pxi", line 1860, in lxml.etree._parseDocumentFromURL (src/lxml/etree.c:121104)
  File "src/lxml/parser.pxi", line 1764, in lxml.etree._parseDocFromFile (src/lxml/etree.c:120012)
  File "src/lxml/parser.pxi", line 1161, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/etree.c:114561)
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/etree.c:107738)
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult (src/lxml/etree.c:109447)
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError (src/lxml/etree.c:108301)
  File "/home/sam/repos/support/ZurichWorkshop2018/source_data/MEEQ_loc.csv", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```

**Comment by sambles** [comment]
not a bug, flags changed from when call was written
