### ISSUE TITLE
API-Worker stuck on error from CSV transforms 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#118]
If the input generation fails at the transform function (Multithread call), then the CLI call will hang, 
causing the worker to block on subsequent file generation requests. 
 
```
Writing canonical exposures file /home/sam/repos/models/piwind/runs/OasisFiles-20181123135201/canexp-20181123135201.csv
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/oasislmf/utils/concurrency.py", line 128, in run
    task.result = task.func(*task.args) if task.args else task.func()
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/oasislmf/exposures/csv_trans.py", line 89, in process_chunk
    data
  File "/home/sam/repos/core/env/py3/lib/python3.6/site-packages/oasislmf/exposures/csv_trans.py", line 114, in csv_to_xml
    rec.set(csv_header[i], row[i])
  File "src/lxml/etree.pyx", line 826, in lxml.etree._Element.set (src/lxml/etree.c:52998)
  File "src/lxml/apihelpers.pxi", line 567, in lxml.etree._setAttributeValue (src/lxml/etree.c:24235)
  File "src/lxml/apihelpers.pxi", line 1643, in lxml.etree._attributeValidOrRaise (src/lxml/etree.c:35582)
ValueError: Invalid attribute name 'Unnamed: 0'
```

**Comment by sambles** [comment]
[Partial fix], trial run a subset of the input data before handing over to the worker threads
