### ISSUE TITLE
Error caused by pandas 2.0.0

### ISSUE THREAD

**Issue by mtazzari** [OasisLMF/OasisLMF#1251]
## Issue Description
When running `oasislmf model run` in PiWind in a clean system installation, it generates the following error:
```bash
Stating oasislmf command - RunModel
RUNNING: oasislmf.manager.interface

  0%|          | 0/2 [00:00<?, ?it/s]
Processing arguments - Creating Oasis Files

Generating Oasis files (GUL=True, IL=True, RIL=True)
RUNNING: oasislmf.lookup.factory.generate_key_files

  0%|          | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/mdm/.local/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/cli/root.py", line 41, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/mdm/.local/lib/python3.10/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/mdm/.local/lib/python3.10/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/mdm/.local/lib/python3.10/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/cli/command.py", line 142, in action
    manager_method(**_kwargs)
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/utils/log.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/manager.py", line 90, in interface
    return computation_cls(**kwargs).run()
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/computation/run/model.py", line 80, in run
    cmd[0](**cmd[1]).run()
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/computation/generate/files.py", line 200, in run
    GenerateKeys(**self.kwargs).run()
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/computation/generate/keys.py", line 122, in run
    res = key_server.generate_key_files(
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/utils/log.py", line 122, in wrapper
    result = func(*args, **kwargs)
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/lookup/factory.py", line 545, in generate_key_files
    return self.generate_key_files_multiproc(locations,
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/lookup/factory.py", line 480, in generate_key_files_multiproc
    return self.generate_key_files_singleproc(loc_df, successes_fp, errors_fp, output_format, keys_success_msg)
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/lookup/factory.py", line 437, in generate_key_files_singleproc
    key_results = lookup.process_locations(loc_df)
  File "/home/mdm/.local/lib/python3.10/site-packages/oasislmf/lookup/builtin.py", line 210, in process_locations
    locations = locations[locations.columns & useful_cols].drop_duplicates()
  File "/home/mdm/.local/lib/python3.10/site-packages/pandas/core/ops/common.py", line 81, in new_method
    return method(self, other)
  File "/home/mdm/.local/lib/python3.10/site-packages/pandas/core/arraylike.py", line 70, in __and__
    return self._logical_method(other, operator.and_)
  File "/home/mdm/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 6791, in _logical_method
    res_values = ops.logical_op(lvalues, rvalues, op)
  File "/home/mdm/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 394, in logical_op
    res_values = na_logical_op(lvalues, rvalues, op)
  File "/home/mdm/.local/lib/python3.10/site-packages/pandas/core/ops/array_ops.py", line 304, in na_logical_op
    result = op(x, y)
ValueError: operands could not be broadcast together with shapes (21,) (7,) 
```
I tracked it down to being caused by `pandas 2.0.0` that was released last week.

The error is not present if I downgrade pandas:
```bash
pip uninstall pandas
pip install "pandas<2"
```

## Steps to Reproduce (Bugs only)
1. launch binder: https://mybinder.org/v2/gh/OasisLMF/OasisPiWind/develop
2. open a terminal window and run `oasislmf model run`

**Comment by sambles** [comment]
needs applying to backports 1.26.x

**Comment by sambles** [comment]
won't backport to 1.26, due to problem in older ods-tools package 
See https://github.com/OasisLMF/OasisLMF/pull/1254
