### ISSUE TITLE
Missing parquet library dependencies for gulmc in 1.27

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#1385]
## Issue Description

It seems that the parquet libraries are required no longer optional for running gulmc in 1.27.5.  Could the missing parquet packages be added to the requirements list please?

## Steps to Reproduce (Bugs only)

1. Run an analysis using gulmc=true in 1.27.5 
2. ModuleNotFoundError: No module named 'pyarrow'

## Version / Environment information

1.27.5
## Example data / logs

ModuleNotFoundError: No module named 'pyarrow'
Traceback (most recent call last):
  File "/home/joh/venv/bin/gulmc", line 5, in <module>
    from oasislmf.pytools.gulmc.cli import main
  File "/home/joh/venv/lib/python3.10/site-packages/oasislmf/pytools/gulmc/cli.py", line 7, in <module>
    from oasislmf.pytools.gulmc import logger, manager
  File "/home/joh/venv/lib/python3.10/site-packages/oasislmf/pytools/gulmc/manager.py", line 20, in <module>
    from oasislmf.pytools.data_layer.footprint_layer import FootprintLayerClient
  File "/home/joh/venv/lib/python3.10/site-packages/oasislmf/pytools/data_layer/footprint_layer.py", line 15, in <module>
    from oasislmf.pytools.getmodel.footprint import Footprint
  File "/home/joh/venv/lib/python3.10/site-packages/oasislmf/pytools/getmodel/footprint.py", line 14, in <module>
    import pyarrow.parquet as pq
ModuleNotFoundError: No module named 'pyarrow'

**Comment by benhayes21** [comment]
move pyarrow to be in required packages
