### ISSUE TITLE
oasislmf model generate-keys: 'loc_id_col' is not defined

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#198]
Running `oasislmf model generate-keys -C oasislmf.json` with the ComplexModelMDK example:

```Traceback (most recent call last):
  File "/home/danielevans/venv/farmcat/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/home/danielevans/venv/farmcat/lib/python2.7/site-packages/oasislmf/cli/root.py", line 40, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/danielevans/venv/farmcat/lib/python2.7/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/danielevans/venv/farmcat/lib/python2.7/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/danielevans/venv/farmcat/lib/python2.7/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/danielevans/venv/farmcat/lib/python2.7/site-packages/oasislmf/cli/model.py", line 203, in action
    keys_format=keys_format
  File "/home/danielevans/venv/farmcat/lib/python2.7/site-packages/oasislmf/utils/log.py", line 125, in wrapper
    result = func(*args, **kwargs)
  File "/home/danielevans/venv/farmcat/lib/python2.7/site-packages/oasislmf/manager.py", line 288, in generate_keys
    loc_id_col=loc_id_col,
NameError: global name 'loc_id_col' is not defined
```

It might just need to be `loc_id_col='locnumber'` like line 382 of manager.py.

**Comment by sr-murthy** [comment]
Which release are you running? This was fixed in release 1.3.1 a few days ago

https://github.com/OasisLMF/OasisLMF/blob/8286a97958b724552d57a3ef745f271784c7f6f5/oasislmf/manager.py#L382

**Comment by sr-murthy** [comment]
@DanielFEvans I think your error has been traced to a different place in the manager, line 288, so there is an upcoming release 1.3.2 today, in which this will be fixed.

**Comment by DanielFEvans** [comment]
Yes, 288 was the line picked out by the traceback above. Thanks.

**Comment by sr-murthy** [comment]
Closing - this should be fine in 1.3.2.
