### ISSUE TITLE
[test model-api]  Download outputs url

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#25]
Test is issuing call to `http://oasis_api_server/outputs/`  when it seems like it should be 
GET /outputs/{location}  | The location of the outputs resource to download.

`wget http://oasis_api_server/outputs/57bb6d2d863b44f3876b42e9f42c65d9`

```
--2018-03-23 16:56:48--  http://oasis_api_server/outputs/57bb6d2d863b44f3876b42e9f42c65d9
Resolving oasis_api_server (oasis_api_server)... 192.168.16.5
Connecting to oasis_api_server (oasis_api_server)|192.168.16.5|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48296 (47K) [application/x-tar]
Saving to: '57bb6d2d863b44f3876b42e9f42c65d9'

57bb6d2d863b44f3876b42e9f42c65d9       100%[=========================================================================>]  47.16K  --.-KB/s    in 0s      

2018-03-23 16:56:48 (668 MB/s) - '57bb6d2d863b44f3876b42e9f42c65d9' saved [48296/48296]

root@db55bf67aa25:/var/www/oasis# file 57bb6d2d863b44f3876b42e9f42c65d9
57bb6d2d863b44f3876b42e9f42c65d9: gzip compressed data, was "57bb6d2d863b44f3876b42e9f42c65d9.tar", last modified: Fri Mar 23 16:29:34 2018, max compression
```

```
root@db55bf67aa25:/var/www/oasis# ./run_api_test_analysis.sh 
STARTED: oasislmf.api_client.client.health_check
COMPLETED: oasislmf.api_client.client.health_check in 0.01s
Loading analysis settings JSON file:
  OK: analysis_settings={u'analysis_settings': {u'source_tag': u'test_source', u'gul_summaries': [{u'aalcalc': False, u'leccalc': {u'return_period_file': False, u'outputs': {u'sample_mean_oep': False, u'sample_mean_aep': False, u'full_uncertainty_oep': False, u'wheatsheaf_aep': False, u'wheatsheaf_mean_aep': False, u'full_uncertainty_aep': False, u'wheatsheaf_mean_oep': False, u'wheatsheaf_oep': False}}, u'eltcalc': True, u'pltcalc': False, u'summarycalc': False, u'id': 1, u'lec_output': False}], u'il_summaries': [{u'aalcalc': False, u'leccalc': {u'return_period_file': False, u'outputs': {u'sample_mean_oep': False, u'sample_mean_aep': False, u'full_uncertainty_oep': False, u'wheatsheaf_aep': False, u'wheatsheaf_mean_aep': False, u'full_uncertainty_aep': False, u'wheatsheaf_mean_oep': False, u'wheatsheaf_oep': False}}, u'eltcalc': True, u'pltcalc': False, u'summarycalc': False, u'id': 1, u'lec_output': False}], u'analysis_tag': u'test_analysis', u'number_of_samples': 100, u'model_version_id': u'1', u'module_supplier_id': u'OasisIM', u'gul_threshold': 100, u'gul_output': True, u'il_output': False, u'prog_id': 1, u'model_settings': {u'event_occurrence_file_id': 1, u'use_random_number_file': True}}}, do_il=False
Running 1 analyses
STARTED: oasislmf.api_client.client.upload_inputs_from_directory
COMPLETED: oasislmf.api_client.client.upload_inputs_from_directory in 0.03s
STARTED: oasislmf.api_client.client.run_analysis_and_poll
STARTED: oasislmf.api_client.client.run_analysis
Analysis started
COMPLETED: oasislmf.api_client.client.run_analysis in 0.0s
Analysis started
STARTED: oasislmf.api_client.client.download_outputs
GET http://oasis_api_server/outputs/ failed: 404
Model API test failed: GET http://oasis_api_server/outputs/ failed: 404
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/oasislmf/cmd/test.py", line 101, in run_analysis
    client.run_analysis_and_poll(analysis_settings, input_location, output_directory)
  File "/usr/local/lib/python2.7/dist-packages/oasislmf/utils/log.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oasislmf/api_client/client.py", line 224, in run_analysis_and_poll
    self.download_outputs(outputs_location, outputs_file)
  File "/usr/local/lib/python2.7/dist-packages/oasislmf/utils/log.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/oasislmf/api_client/client.py", line 318, in download_outputs
    self.download_resource('/outputs/' + outputs_location, localfile)
  File "/usr/local/lib/python2.7/dist-packages/oasislmf/api_client/client.py", line 286, in download_resource
    raise OasisException(exception_message)
OasisException: GET http://oasis_api_server/outputs/ failed: 404
Finished: 0 completed, 1 failed
```

**Comment by sambles** [comment]
This seems to happen because the call `oasislmf.api_client.client.download_outputs`  was made before the analysis had completed.
