### ISSUE TITLE
FM: grouping to account level issue

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#294]
The grouping of locations to accounts in fm_programme seems to have gone wrong for validation/example/FA45_149. 

below is the fm_programme file with the reference information for to_agg_id (from fm_summary_map). note that the level 3 mapping from location to account is inconsistent with the account numbers. I expect instead 1,2,2,3,3, for the level 3 to_agg_id

	from_agg_id,level_id,to_agg_id,coverage_type_id,locnumber,accnumber
	1,1,1,1,FA45_01_1,FA45_01
	2,1,2,3,FA45_01_1,FA45_01
	3,1,3,4,FA45_01_1,FA45_01
	4,1,4,1,FA45_02_1,FA45_02
	5,1,5,3,FA45_02_1,FA45_02
	6,1,6,4,FA45_02_1,FA45_02
	7,1,7,1,FA45_02_2,FA45_02
	8,1,8,3,FA45_02_2,FA45_02
	9,1,9,4,FA45_02_2,FA45_02
	10,1,10,1,SS01_04_1,SS01_04
	11,1,11,3,SS01_04_1,SS01_04
	12,1,12,4,SS01_04_1,SS01_04
	13,1,13,1,SS01_04_2,SS01_04
	14,1,14,3,SS01_04_2,SS01_04
	15,1,15,4,SS01_04_2,SS01_04
	1,2,1,,FA45_01_1,FA45_01
	2,2,1,,FA45_01_1,FA45_01
	3,2,1,,FA45_01_1,FA45_01
	4,2,2,,FA45_02_1,FA45_02
	5,2,2,,FA45_02_1,FA45_02
	6,2,2,,FA45_02_1,FA45_02
	7,2,3,,FA45_02_2,FA45_02
	8,2,3,,FA45_02_2,FA45_02
	9,2,3,,FA45_02_2,FA45_02
	10,2,4,,SS01_04_1,SS01_04
	11,2,4,,SS01_04_1,SS01_04
	12,2,4,,SS01_04_1,SS01_04
	13,2,5,,SS01_04_2,SS01_04
	14,2,5,,SS01_04_2,SS01_04
	15,2,5,,SS01_04_2,SS01_04
	1,3,1,,,FA45_01
	2,3,1,,,FA45_02
	3,3,2,,,FA45_02
	4,3,2,,,SS01_04
	5,3,3,,,SS01_04

I also get an error when running this example using `oasislmf exposure run`

	Traceback (most recent call last):
	  File "/home/joh/git/OasisLMF/venv3/bin/oasislmf", line 7, in <module>
	    sys.exit(RootCmd().run())
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/cli/root.py", line 39, in run
	    return super(OasisBaseCommand, self).run(args=args)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
	    return cmd_cls(sub_command_name).run(args)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
	    return cmd_cls(sub_command_name).run(args)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
	    return self.action(args) or 0
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/cli/exposure.py", line 133, in action
	    alloc_rule=alloc_rule
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
	    result = func(*args, **kwargs)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/manager.py", line 760, in run_deterministic
	    ri_scope_fp=ri_scope_fp
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
	    result = func(*args, **kwargs)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/manager.py", line 487, in generate_oasis_files
	    ri_info_df, ri_scope_df, _ = load_oed_dfs(ri_info_fp, ri_scope_fp)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/model_preparation/oed.py", line 189, in load_oed_dfs
	    col_dtypes=RI_SCOPE_DTYPES)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/utils/data.py", line 322, in get_dataframe
	    df = set_dataframe_column_dtypes(df, _col_dtypes)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/utils/data.py", line 530, in set_dataframe_column_dtypes
	    df = df.astype(_dtypes)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/pandas/core/generic.py", line 5678, in astype
	    results.append(col.astype(dtype[col_name], copy=copy))
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/pandas/core/generic.py", line 5691, in astype
	    **kwargs)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 531, in astype
	    return self.apply('astype', dtype=dtype, **kwargs)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 395, in apply
	    applied = getattr(b, f)(**kwargs)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 534, in astype
	    **kwargs)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 633, in _astype
	    values = astype_nansafe(values.ravel(), dtype, copy=True)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 676, in astype_nansafe
	    raise ValueError('Cannot convert non-finite values (NA or inf) to '
	ValueError: Cannot convert non-finite values (NA or inf) to integer

**Comment by sr-murthy** [comment]
@johcarter The two issues here don't appear to be related. The runtime error appears to be caused by a missing or incorrect or null value in the RI info. or scope. files

    ...
	File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/manager.py", line 487, in generate_oasis_files
	    ri_info_df, ri_scope_df, _ = load_oed_dfs(ri_info_fp, ri_scope_fp)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/model_preparation/oed.py", line 189, in load_oed_dfs
	    col_dtypes=RI_SCOPE_DTYPES)
	  File "/home/joh/git/OasisLMF/venv3/lib/python3.6/site-packages/oasislmf/utils/data.py", line 322, in get_dataframe
	    df = set_dataframe_column_dtypes(df, _col_dtypes)
    ...

In relation to the FM programme file, firstly, I don't know what level 3 is here - the values in the `level_id` column are FM level IDs reindexed from 1, after removing any "intermediate" FM levels for which there are no financial terms, which means level 3 doesn't necessarily mean the "Site All" level in the OED hierarchy. But you should be aware that the values in the `to_agg_id` column (and also  the `from_agg_id` column) in this file are sourced from the `agg_id` column in the IL inputs table, and `agg_id` is generated via an aggregation profile which is located here

https://github.com/OasisLMF/OasisLMF/blob/fix/calc-rules-and-layer-ids/oasislmf/_data/default_fm_agg_profile.json

In the IL inputs table, items in each FM level are grouped by a composite key made of columns from the table, and `agg_id` is simply a map from items to the index ID of the corresponding aggregation group. The profile defines the aggregation keys by level and the code just uses the profile.

	FM level #		Agg. key
	==========		========
	(1) Site coverage	GUL input item ID
	(2) Site PD		Loc. number, BI coverage bool
	(3) Site all		Loc. number
	(6) Cond. all		Portfolio num., Acc. num., Cond. num.
	(9) Policy all		Portfolio num., Acc. num.
	(10) Policy layer	Portfolio num., Acc. num.

As loc. number doesn't uniquely identify rows, we probably need to update the aggregation keys for the site PD (#2), and site all (#3) levels to include portfolio num. and acc. num. This can be easily fixed - I will update the agg. profile next week.

**Comment by johcarter** [comment]
On your last point, yes that sounds like the cause. I managed to fix the problem with the reinsurance files, so its now just the aggregation key issue. thanks

**Comment by johcarter** [comment]
Fixed
