### ISSUE TITLE
Obscure error message if LocPerilsCovered is empty

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#296]
In OasisLMF v1.3.8, I am trying to run a small 1-row portfolio with `oasislmf model run`.

At the end of the inputs generation, I receive the following traceback:

```
Traceback (most recent call last):
  File "/home/farm/gloflomo_venv/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/oasislmf/cli/root.py", line 39, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/oasislmf/cli/model.py", line 597, in action
    cmd.action(args)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/oasislmf/cli/model.py", line 352, in action
    user_data_dir=user_data_dir
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/oasislmf/manager.py", line 431, in generate_oasis_files
    oed_hierarchy=oed_hierarchy
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/oasislmf/model_preparation/summaries.py", line 585, in write_exposure_summary
    exposure_df[loc_per_cov].str.split(';').to_list(),
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/pandas/core/generic.py", line 5063, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/pandas/core/accessor.py", line 171, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/pandas/core/strings.py", line 1796, in __init__
    self._validate(data)
  File "/home/farm/gloflomo_venv/lib/python3.6/site-packages/pandas/core/strings.py", line 1818, in _validate
    raise AttributeError("Can only use .str accessor with string "
AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas
```

The line:
`exposure_df[loc_per_cov].str.split(';')`
is attempting to access the 'LocPerilID' column of the OED. While it is present in my portfolio, it is blank, and has been read by Pandas as a float column containing only `NaN`, rather than a string type as expected.

This is likely due to invalid portfolio data on my part (is there some documentation somewhere which states this column must have values?), but a more helpful error message would be useful.

The test portfolio is:
For reference/debugging, my one-row exposures file contains:

```
LocNumber,AccNumber,PortNumber,LocName,OccupancyCode,Longitude,Latitude,BuildingTIV,NumberOfBuildings,PostalCode,LocPerilsCovered,CountryCode,BITIV,ContentsTIV,OtherTIV,LocDed1Building,LocLimit1Building,LocDed2Other,LocLimit2Other,LocDed3Contents,LocLimit3Contents,LocDed4BI,LocLimit4BI
1,1,1,C1R1,1050,99.73613171,19.44940792,300,1,,,,,,,,,,,,,,
```

**Comment by DanielFEvans** [comment]
For reference/debugging, my one-row exposures file contains:

```
LocNumber,AccNumber,PortNumber,LocName,OccupancyCode,Longitude,Latitude,BuildingTIV,NumberOfBuildings,PostalCode,LocPerilsCovered,CountryCode,BITIV,ContentsTIV,OtherTIV,LocDed1Building,LocLimit1Building,LocDed2Other,LocLimit2Other,LocDed3Contents,LocLimit3Contents,LocDed4BI,LocLimit4BI
1,1,1,C1R1,1050,99.73613171,19.44940792,300,1,,,,,,,,,,,,,,
```

**Comment by johcarter** [comment]
hi Daniel, LocPerilsCovered is a required field and invalid if blank . you can see the detailed requirements here;
https://github.com/Simplitium/OED
in the spreadsheet there is a tab OED Input Fields

I think there is a task to add more validation to input files in future. there is alot to do here.

For now, use the value OO1 which means all perils.

**Comment by hchagani-oasislmf** [comment]
At the moment, peril groups such as OO1 and AA1 are ignored by the `write_exposure_summary` method. The only thing this would affect is the contents of `exposure_summary_report.json`. There is a fix in the pipeline for this. However, this issue has no bearing on any of the other output files so shouldn't affect you.

I think `AA1` is the peril group representing all perils.

**Comment by DanielFEvans** [comment]
Thanks both - the reminder about the existence of that spreadsheet tab is very useful. Looks like there's a couple more fields which I need to populate.

**Comment by mpinkerton-oasis** [comment]
@DanielFEvans can this be closed now?

**Comment by DanielFEvans** [comment]
I'm not aware of a change having been made to OasisLMF that means a clear error message is given if the peril code is missing, so I presume the same error would still come up - our users wouldn't stand a chance of identifying the problem if this came out in the log file!

**Comment by mpinkerton-oasis** [comment]
Modex is currently working on some validation utilities for OED files. I think this is where the input data will be validated with clear user output.

**Comment by DanielFEvans** [comment]
Ah, yes, I remember you mentioning that in the past.

I'd still advocate for nice error messages (makes everyone's life easier!), but equally once you know how to format the OED correctly it's a problem that doesn't come up again, so you could close if you think it's solely a ModEx/Nasdaq concern.

**Comment by mpinkerton-oasis** [comment]
Closing as no fix. A full OED validation implementation will be added in due course, in collaboration with Modex dev team.
