### ISSUE TITLE
Keys lookup configuration location

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#300]
The keys configuration only finds the index files if they are in the same location as the keys_data. If, say, you put it in the root directory of the model repo then then it doesn't get picked up even if you configure the paths correctly.

**Comment by sr-murthy** [comment]
Is this the lookup JSON for the built-in lookup framework?

**Comment by sr-murthy** [comment]
All file paths are resolved relative to the keys data path, and the keys data path is set by setting the value of the `keys_data_path` key in the lookup JSON. The path of the Rtree file index is given by the value of the following key
```
 "filename": "%%KEYS_DATA_PATH%%/<index file name>",
```
in the `rtree_index` subsection of the `peril` section of the lookup JSON.

The file path is NOT the path of the AP dict CSV.

**Comment by sr-murthy** [comment]
The AP file index is data needed for the built-in keys lookup. It is therefore considered part of "keys data", and therefore its path is resolved relative to the location of the keys data. You cannot put it at the root of the model repo.

**Comment by mpinkerton-oasis** [comment]
If you have the oasislmf.json in the root directory and the lookup.json and index files in the keys_data folder with keys_data_path = . - this works. If you have oasislmf.json and the lookup.json in the root directory and index files in the keys_data folder with keys_data_path = keys_data_path relative to the root - this doesn't work.

**Comment by sr-murthy** [comment]
It is helpful to post the actual lookup JSON you're using, and the error you're getting. There are two files that make up the index, the `.idx` and `.dat` files. If both are present in your "keys data" folder, wherever that is, and the path of that folder has been specified as the value of `keys_data_path` in the lookup JSON, then it should work.

**Comment by mpinkerton-oasis** [comment]
2019-06-04 11:16:33,100 - root - ERROR - No Rtree file index /home/pinkerton/git/Workshop2019/gem/area-peril.{idx, dat} found
Traceback (most recent call last):
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/cli/root.py", line 39, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/cli/model.py", line 597, in action
    cmd.action(args)
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/cli/model.py", line 352, in action
    user_data_dir=user_data_dir
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/manager.py", line 405, in generate_oasis_files
    output_directory=target_dir
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/model_preparation/lookup.py", line 463, in create
    loc_id_col=loc_id_col
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/model_preparation/lookup.py", line 784, in __init__
    loc_id_col=self.loc_id_col
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/pinkerton/.virtualenvs/Workshop2019/lib/python3.6/site-packages/oasislmf/model_preparation/lookup.py", line 907, in __init__
    raise OasisException('No Rtree file index {}.{{{}, {}}} found'.format(index_fp, idx_ext, dat_ext))

[lookup.json.txt](https://github.com/OasisLMF/OasisLMF/files/3251759/lookup.json.txt)
[oasislmf.json.txt](https://github.com/OasisLMF/OasisLMF/files/3251760/oasislmf.json.txt)
[tree.txt](https://github.com/OasisLMF/OasisLMF/files/3251761/tree.txt)

**Comment by sr-murthy** [comment]
I have reproduced this problem using PiWind - it requires a fix.

**Comment by sr-murthy** [comment]
This has been fixed.
