### ISSUE TITLE
Run analysis fails with Python 3.6

### ISSUE THREAD

**Issue by mpinkerton-oasis** [OasisLMF/OasisLMF#31]
I tried to run PiWind test analysis using:
oasislmf model run -C mdk-oasislmf-piwind.json -r /tmp/analysis_test

Gave the following error:
Creating temporary folder /tmp/analysis_test/tmp for Oasis files
Getting model info and creating lookup service instance
Traceback (most recent call last):
  File "/home/pinkerton/tutorial-env/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/home/pinkerton/tutorial-env/lib/python3.5/site-packages/oasislmf/cmd/root.py", line 36, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/pinkerton/tutorial-env/lib/python3.5/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/pinkerton/tutorial-env/lib/python3.5/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/pinkerton/tutorial-env/lib/python3.5/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/pinkerton/tutorial-env/lib/python3.5/site-packages/oasislmf/cmd/model.py", line 473, in action
    gen_oasis_files_cmd.action(args)
  File "/home/pinkerton/tutorial-env/lib/python3.5/site-packages/oasislmf/cmd/model.py", line 231, in action
    lookup_package_path=lookup_package_file_path,
  File "/home/pinkerton/tutorial-env/lib/python3.5/site-packages/oasislmf/keys/lookup.py", line 260, in create
    lookup_package = cls.get_lookup_package(lookup_package_path)
  File "/home/pinkerton/tutorial-env/lib/python3.5/site-packages/oasislmf/keys/lookup.py", line 138, in get_lookup_package
    lookup_package = importlib.import_module(package_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/tmp/OasisPiWind/src/keys_server/__init__.py", line 6, in <module>
    from utils import *
ImportError: No module named 'utils'

**Comment by sr-murthy** [comment]
I think replacing

    from utils import *

with

    from .utils import *

will fix it.

**Comment by sr-murthy** [comment]
I've just updated PiWind. You can try again.
