### ISSUE TITLE
Division by zero when generating input (degenerate case)

### ISSUE THREAD

**Issue by rtahiry** [OasisLMF/OasisLMF#375]
A division by zero error is thrown when generating oasis input and there is not success (i.e all key lookups result in fail or nomatch).
```[2019-08-12 06:19:02,834: ERROR/ForkPoolWorker-1] Task generate_input[3fb1256b-a613-4bc9-8a1b-3b6336d27049] raised unexpected: ZeroDivisionError('division by zero',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/worker/src/model_execution_worker/tasks.py", line 321, in generate_input
    GenerateOasisFilesCmd(argv=run_args).run()
  File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/usr/local/lib/python3.6/site-packages/oasislmf/cli/model.py", line 355, in action
    summarise_exposure=summarise_exposure
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/manager.py", line 451, in generate_oasis_files
    oasis_files_prefixes=files_prefixes['gul']
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/model_preparation/gul_inputs.py", line 448, in write_gul_input_files
    getattr(this_module, 'write_{}_file'.format(fn))(gul_inputs_df.copy(deep=True), gul_input_files[fn], chunksize)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/model_preparation/gul_inputs.py", line 335, in write_complex_items_file
    index=False
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 3020, in to_csv
    formatter.save()
  File "/usr/local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 172, in save
    self._save()
  File "/usr/local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 280, in _save
    chunks = int(nrows / chunksize) + 1
ZeroDivisionError: division by zero```

**Comment by sr-murthy** [comment]
@rtahiry @sambles The reason why this happens is that the keys file is empty - GUL input files generation is based on joining the loc. dataframe (loaded from the loc. file) with the keys dataframe (loaded from the keys file) on `loc_id` (which is a composite index on `portnumber`, `accnumber` and `locnumber`). Normally, both files and therefore dataframes will contain the `loc_id` column, so this would not be the problem. If the keys file is empty however, there is a probem because then the join between the dataframes will be empty, which will ultimately cause that division by zero error because `chunksize` will be `0`.

The keys file can be empty if the lookup fails on every single location in the loc. file.

**Comment by sambles** [comment]
Fix for chunksize:
https://github.com/OasisLMF/OasisLMF/commit/cbe113955ac653304773ace027537fa4d87f61b2

Added check for empty dataframe after dropping rows with `TIV==0`
https://github.com/OasisLMF/OasisLMF/pull/379/commits/f06c39498d2969d37fe7a21dfd2ee40259a4b025
