### ISSUE TITLE
Issue in write_exposure_summary

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#388]
**Run: oasislmf==1.4.0**
```oasislmf model generate-oasis-files --config oasislmf.json --source-exposure-file-path tests/data/SourceLocOEDNewPiWind.csv --summarise-exposure```

**Trace:**
```
Processing arguments

Generating Oasis files (GUL=True, IL=True, RIL=True)
STARTED: oasislmf.manager.__init__
COMPLETED: oasislmf.manager.__init__ in 0.0s
STARTED: oasislmf.manager.generate_oasis_files
STARTED: oasislmf.model_preparation.lookup.__init__
STARTED: oasislmf.model_preparation.lookup.__init__
COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.0s
STARTED: oasislmf.model_preparation.lookup.__init__
STARTED: oasislmf.model_preparation.lookup.__init__
COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.0s
COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.0s
STARTED: oasislmf.model_preparation.lookup.__init__
STARTED: oasislmf.model_preparation.lookup.__init__
COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.0s
STARTED: oasislmf.model_preparation.lookup.get_vulnerabilities
COMPLETED: oasislmf.model_preparation.lookup.get_vulnerabilities in 0.09s
COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.09s
COMPLETED: oasislmf.model_preparation.lookup.__init__ in 0.09s
STARTED: oasislmf.model_preparation.lookup.bulk_lookup
COMPLETED: oasislmf.model_preparation.lookup.bulk_lookup in 0.0s
STARTED: oasislmf.model_preparation.gul_inputs.get_gul_input_items
COMPLETED: oasislmf.model_preparation.gul_inputs.get_gul_input_items in 1.9s
STARTED: oasislmf.model_preparation.summaries.write_exposure_summary
STARTED: oasislmf.model_preparation.gul_inputs.get_gul_input_items
COMPLETED: oasislmf.model_preparation.gul_inputs.get_gul_input_items in 0.34s
Traceback (most recent call last):
  File "/home/sam/repos/env/3py/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/oasislmf/cli/root.py", line 41, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/oasislmf/cli/model.py", line 355, in action
    summarise_exposure=summarise_exposure
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/oasislmf/manager.py", line 435, in generate_oasis_files
    oed_hierarchy=oed_hierarchy
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/oasislmf/model_preparation/summaries.py", line 740, in write_exposure_summary
    index=exp_perils_df.index
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/pandas/core/frame.py", line 435, in __init__
    arrays, columns = to_arrays(data, columns, dtype=dtype)
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 404, in to_arrays
    dtype=dtype)
  File "/home/sam/repos/env/3py/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 434, in _list_to_arrays
    content = list(lib.to_object_array(data).T)
  File "pandas/_libs/lib.pyx", line 2265, in pandas._libs.lib.to_object_array
TypeError: object of type 'float' has no len()
```

https://github.com/OasisLMF/OasisLMF/blob/develop/oasislmf/model_preparation/summaries.py#L751-L754

**Comment by hchagani-oasislmf** [comment]
Invalid peril code of `V` given in `loc` file on line no. 9948. Could introduce something into code to catch invalid peril codes. However, OED validation package should catch this in future. Suggest changing code to `WW1` for now in `loc` file.

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisPiWind/commit/8476241b71d3b757c65c2fa608173dd8f337d63a
