### ISSUE TITLE
GEM - error in lookup 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#483]
Blank values in ['constructioncode', 'numberofstoreys'] crashes with:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/worker/src/model_execution_worker/tasks.py", line 375, in generate_input
    GenerateOasisFilesCmd(argv=run_args).run()
  File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/usr/local/lib/python3.6/site-packages/oasislmf/cli/model.py", line 263, in action
    write_chunksize=write_chunksize
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/manager.py", line 503, in generate_oasis_files
    errors_fp=_keys_errors_fp
  File "/usr/local/lib/python3.6/site-packages/oasislmf/model_preparation/lookup.py", line 767, in save_results
    results = keys_generator(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/model_preparation/lookup.py", line 652, in get_keys_multiproc
    results = pool.map(lookup.process_locations_multiproc, locations)
  File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 1375, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/lib/python3.6/site-packages/billiard/pool.py", line 1745, in get
    raise self._value.exception
ValueError: Cannot convert non-finite values (NA or inf) to integer
```

from: 
https://github.com/OasisLMF/gem/blob/25ae0acbca3dc7b5fc742209f664afb5284683b1/src/keys_server/GMO/GMOKeysLookup.py#L189-L193

Fix: Replace N/A blank columns before sending location data to a models lookup class

**Comment by DanielFEvans** [comment]
For some columns (both of those mentioned here), there are OED defaults, but are you intending to map N/A values to something else for other columns? There are a handful of columns that are int type, and many more of string types, that specify no default.

**Comment by sambles** [comment]
> There are a handful of columns that are int type, and many more of string types, that specify no default.  

Good point, I'm not sure what the best option for detailing partial data is in that case

**Comment by DanielFEvans** [comment]
Pandas v1.0.0 now has support for Integer N/A values, which seems useful.

Pandas can put np.nan in String columns, but it'd still be up to the model developer to handle this - blindly assuming they're strings could end badly.

**Comment by mpinkerton-oasis** [comment]
@sambles can this be closed?
