### ISSUE TITLE
Pandas==1.0 error 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#486]
Problem 1: error hidden unless run with `--verbose`
Problem 2: see below 

```
2020-01-30 16:19:44,993 - root - ERROR - 
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/oasislmf/model_preparation/il_inputs.py", line 583, in get_il_input_items
    il_inputs_df['calcrule_id'] = get_calc_rule_ids(il_inputs_df)
  File "/root/.local/lib/python3.8/site-packages/oasislmf/model_preparation/il_inputs.py", line 75, in get_calc_rule_ids
    il_inputs_calc_rules_df = il_inputs_df.loc[:, ['item_id'] + terms + terms_indicators + types_and_codes + ['calcrule_id']]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1760, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1287, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1952, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1593, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1550, in _get_listlike_indexer
    self._validate_read_indexer(
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 1652, in _validate_read_indexer
    raise KeyError(
KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/oasislmf/cli/root.py", line 41, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/root/.local/lib/python3.8/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/root/.local/lib/python3.8/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/root/.local/lib/python3.8/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/root/.local/lib/python3.8/site-packages/oasislmf/cli/model.py", line 248, in action
    oasis_files = om().generate_oasis_files(
  File "/root/.local/lib/python3.8/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/oasislmf/manager.py", line 562, in generate_oasis_files
    il_inputs_df, _ = get_il_input_items(
  File "/root/.local/lib/python3.8/site-packages/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/oasislmf/model_preparation/il_inputs.py", line 598, in get_il_input_items
    raise OasisException from e
oasislmf.utils.exceptions.OasisException
```

**Comment by sambles** [comment]
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
