### ISSUE TITLE
Non-unicode CSV data is not handled neatly

### ISSUE THREAD

**Issue by DanielFEvans** [OasisLMF/OasisLMF#565]
One of our users tried to run OasisLMF with a portfolio encoded in Latin-1 (thanks to Excel), rather than UTF8, which resulted in the error below. This isn't an issue specific to anything done in OasisLMF - I think Python always assumes that text files are UTF8 (or ASCII) encoded unless told otherwise, and trying to read a Latin-1 encoded file even in plain Python ends with similar UnicodeDecodeErrors.

Would it be worth considering implementing one of:
A) Adding a try-catch in `oasislmf.utils.data.get_dataframe`, with a slightly nicer error suggesting that the data has some unexpected encoding, or,
B) Using a library like `chardet` to automatically detect the encoding.

However, in either case, there'd still be the problem of a model vendor's pre-processing code being exposed to the raw files, too.

(Does OasisPlatform have better handling for non-UTF8/ASCII file encodings, hence avoiding this problem if it's not run from the command line?)

```
Traceback (most recent call last):

File "/home/farm/farmcatenv/bin/oasislmf", line 7, in <module>
  sys.exit(RootCmd().run())
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/oasislmf/cli/root.py", line 41, in run
  return super(OasisBaseCommand, self).run(args=args)
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
  return cmd_cls(sub_command_name).run(args)
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
  return cmd_cls(sub_command_name).run(args)
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
  return self.action(args) or 0
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/oasislmf/cli/model.py", line 489, in action
  cmd.action(args)
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/oasislmf/cli/model.py", line 270, in action
  group_id_cols=group_id_cols
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/oasislmf/utils/log.py", line 106, in wrapper
  result = func(*args, **kwargs)
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/oasislmf/manager.py", line 512, in generate_oasis_files
  source_exposure_fp=exposure_fp,
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/oasislmf/model_preparation/lookup.py", line 410, in get_exposure
  required_cols=required_cols
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/oasislmf/utils/data.py", line 325, in get_dataframe
  headers = list(pd.read_csv(src_fp).head(0))
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
  return _read(filepath_or_buffer, kwds)
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 435, in _read
  data = parser.read(nrows)
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 1139, in read
  ret = self._engine.read(nrows)
File "/home/farm/farmcatenv/lib64/python3.6/site-packages/pandas/io/parsers.py", line 1995, in read
  data = self._reader.read(nrows)
File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
File "pandas/_libs/parsers.pyx", line 991, in pandas._libs.parsers.TextReader._read_rows
File "pandas/_libs/parsers.pyx", line 1123, in pandas._libs.parsers.TextReader._convert_column_data
File "pandas/_libs/parsers.pyx", line 1176, in pandas._libs.parsers.TextReader._convert_tokens
File "pandas/_libs/parsers.pyx", line 1299, in pandas._libs.parsers.TextReader._convert_with_dtype
File "pandas/_libs/parsers.pyx", line 1315, in pandas._libs.parsers.TextReader._string_convert
File "pandas/_libs/parsers.pyx", line 1553, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 1: invalid continuation byte
```

[loc_latin1_example.zip](https://github.com/OasisLMF/OasisLMF/files/4650648/loc_latin1_example.zip)

**Comment by sambles** [comment]
The Django file storage class in OasisPlatform can handle the example file, although i'm not sure how robust it is vs other encoding types.

A quick upload/down check on your example file yields:
```
file loc_latin1_api_download.csv
loc_latin1_api_download.csv: UTF-8 Unicode text, with very long lines, with CRLF line terminators
```

We should also handle this in the MDK, at a minimum (A) where we prompt
`<file> is an unknown encoding .. etc`

I do like the `chardet` and it should be straightforward to add.

**Comment by sambles** [comment]
Added chardet detect with https://github.com/OasisLMF/OasisLMF/commit/303d777bf88a78c78c1e2e509893211819dd50dd
