### ISSUE TITLE
Arch2020 - Issue running leccalc in complex Models

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#620]
Issue running complex models, in the report creation task:

`eltcal`, `aalcalc` and `pltcalc` look fine, it fails when calling `leccalc`
```
output # ls -la
total 808
drwxr-xr-x 2 root root   4096 Jul 24 15:17 .
drwxr-xr-x 8 root root   4096 Jul 24 15:31 ..
-rw-r--r-- 1 root root    155 Jul 24 15:17 gul_S1_aalcalc.csv
-rw-r--r-- 1 root root  70140 Jul 24 15:17 gul_S1_eltcalc.csv
-rw-r--r-- 1 root root      0 Jul 24 15:17 gul_S1_leccalc_full_uncertainty_aep.csv
-rw-r--r-- 1 root root      0 Jul 24 15:17 gul_S1_leccalc_full_uncertainty_oep.csv
-rw-r--r-- 1 root root 736894 Jul 24 15:17 gul_S1_pltcalc.csv
-rw-r--r-- 1 root root     33 Jul 24 15:16 gul_S1_summary-info.csv

```

```
[2020-07-24 15:17:45,720: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-0.tar.gz
[2020-07-24 15:17:45,723: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-1.tar.gz
[2020-07-24 15:17:45,738: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-2.tar.gz
[2020-07-24 15:17:45,758: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-3.tar.gz
[2020-07-24 15:17:45,779: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-4.tar.gz
[2020-07-24 15:17:45,796: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-5.tar.gz
[2020-07-24 15:17:45,811: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-6.tar.gz
[2020-07-24 15:17:45,825: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-7.tar.gz
[2020-07-24 15:17:45,842: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-8.tar.gz
[2020-07-24 15:17:45,857: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-9.tar.gz
[2020-07-24 15:17:45,875: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-10.tar.gz
[2020-07-24 15:17:45,885: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-11.tar.gz
[2020-07-24 15:17:45,896: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-12.tar.gz
[2020-07-24 15:17:45,909: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-13.tar.gz
[2020-07-24 15:17:45,920: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-14.tar.gz
[2020-07-24 15:17:45,927: INFO/ForkPoolWorker-1] Get shared file: /shared-fs/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/work-15.tar.gz
[2020-07-24 15:17:45,936: INFO/ForkPoolWorker-1] STARTED: oasislmf.manager.__init__
[2020-07-24 15:17:45,936: INFO/ForkPoolWorker-1] COMPLETED: oasislmf.manager.__init__ in 0.0s
[2020-07-24 15:17:45,937: INFO/ForkPoolWorker-1] STARTED: oasislmf.model_execution.runner.run_outputs
[2020-07-24 15:17:47,356: INFO/ForkPoolWorker-1] 
BASH_TRACE:
+ lpid1=296
+ aalcalc -Kgul_S1_summaryaalcalc
+ lpid2=298
+ wait 296 298
+ leccalc -r -Kgul_S1_summaryleccalc -F output/gul_S1_leccalc_full_uncertainty_aep.csv -f output/gul_S1_leccalc_full_uncertainty_oep.csv
FATAL: Stream read error: samplesize

[2020-07-24 15:17:47,356: INFO/ForkPoolWorker-1] 
STDOUT:

[2020-07-24 15:17:47,362: WARNING/ForkPoolWorker-1] /usr/local/lib/python3.8/site-packages/pymysql/cursors.py:170: Warning: (1300, "Invalid utf8mb4 character string: '800595'")
  result = self._query(query)
[2020-07-24 15:17:47,370: ERROR/ForkPoolWorker-1] Task generate_losses_output[89404e9a-2b11-496e-9551-42533daff7cc] raised unexpected: OasisException('Ktools run Error: non-zero exit code or output detected on STDERR\nLogs stored in: /tmp/run/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/run-data/log')
Traceback (most recent call last):
  File "/home/worker/src/oasislmf/oasislmf/manager.py", line 1196, in run_loss_outputs
    return model_runner_module.run_outputs(**params)
  File "/home/worker/src/oasislmf/oasislmf/utils/log.py", line 106, in wrapper
    result = func(*args, **kwargs)
  File "/home/worker/src/oasislmf/oasislmf/model_execution/runner.py", line 187, in run_outputs
    bash_trace = subprocess.check_output(['bash', params['filename']]).decode('utf-8')
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bash', '/tmp/run/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/run-data/run_ktools.sh']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/worker/src/model_execution_worker/tasks.py", line 637, in run
    return fn(self, params, *args, analysis_id=analysis_id, **kwargs)
  File "/home/worker/src/model_execution_worker/tasks.py", line 733, in generate_losses_output
    OasisManager().run_loss_outputs(**res)
  File "/home/worker/src/oasislmf/oasislmf/manager.py", line 1216, in run_loss_outputs
    raise OasisException(
oasislmf.utils.exceptions.OasisException: Ktools run Error: non-zero exit code or output detected on STDERR
Logs stored in: /tmp/run/analysis-22_losses-a5ba26973dc24c8792b4ce6cc825591e/run-data/log
```

```
log # cat bash.log 
+ lpid1=296
+ aalcalc -Kgul_S1_summaryaalcalc
+ lpid2=298
+ wait 296 298
+ leccalc -r -Kgul_S1_summaryleccalc -F output/gul_S1_leccalc_full_uncertainty_aep.csv -f output/gul_S1_leccalc_full_uncertainty_oep.csv
FATAL: Stream read error: samplesize
```

**Comment by sambles** [comment]
Cause:
```
oasis-worker(86a74a8587f0) /tmp/run/analysis-26_losses-4892b6b79d0e41a3b92f0fed491b3965/run-data/work/kat # ls -la
total 21584
drwxr-xr-x 2 root root    4096 Jul 27 10:54 .
drwxr-xr-x 5 root root    4096 Jul 27 10:54 ..
-rw-r--r-- 1 root root       0 Jul 27 10:54 gul_S1_eltcalc_P0
-rw-r--r-- 1 root root  354544 Jul 27 10:54 gul_S1_eltcalc_P1
-rw-r--r-- 1 root root  371700 Jul 27 10:54 gul_S1_eltcalc_P2
-rw-r--r-- 1 root root  294244 Jul 27 10:54 gul_S1_eltcalc_P3
-rw-r--r-- 1 root root  301671 Jul 27 10:54 gul_S1_eltcalc_P4
-rw-r--r-- 1 root root  252006 Jul 27 10:54 gul_S1_eltcalc_P5
-rw-r--r-- 1 root root  220820 Jul 27 10:54 gul_S1_eltcalc_P6
-rw-r--r-- 1 root root  243723 Jul 27 10:54 gul_S1_eltcalc_P7
-rw-r--r-- 1 root root       0 Jul 27 10:54 gul_S1_pltcalc_P0
-rw-r--r-- 1 root root 3158360 Jul 27 10:54 gul_S1_pltcalc_P1
-rw-r--r-- 1 root root 3245227 Jul 27 10:54 gul_S1_pltcalc_P2
-rw-r--r-- 1 root root 3192950 Jul 27 10:54 gul_S1_pltcalc_P3
-rw-r--r-- 1 root root 3229812 Jul 27 10:54 gul_S1_pltcalc_P4
-rw-r--r-- 1 root root 2719905 Jul 27 10:54 gul_S1_pltcalc_P5
-rw-r--r-- 1 root root 1941363 Jul 27 10:54 gul_S1_pltcalc_P6
-rw-r--r-- 1 root root 2542043 Jul 27 10:54 gul_S1_pltcalc_P7
```

**Comment by sambles** [comment]
https://github.com/OasisLMF/OasisLMF/commit/919df638567dd864db655debf0a26afb155405ed
https://github.com/OasisLMF/OasisPlatform/commit/3eb81fec19986d2fe3beb6c1a8cda35eb6cefdb8
