### ISSUE TITLE
Issue in FM programme file generation

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisLMF#623]
Issue in creating the FM hierarchy. 

Legacy systems has a two levels of while oasislmf creates an incomplete 2nd level is which results in `ValueError: Cannot convert non-finite values (NA or inf) to integer`

[Oasislmf FM files](https://files.slack.com/files-pri/T53C6P8Q6-F01861L5E2G/download/bf0d1a98d8264f75a2d721809945d27b.tar.gz)
[Example Legacy generation](https://files.slack.com/files-pri/T53C6P8Q6-F017YUAFLP7/download/vb_api18_01_cor_-_cn_1139068tempaggloc_test_samples3_disag_indp_loc_-_14-07-2020_-_19_34_47-input-files.zip)

### Stack trace 
```
RUNNING: oasislmf.model_preparation.gul_inputs.get_gul_input_items
RUNNING: oasislmf.model_preparation.summaries.write_exposure_summary
RUNNING: oasislmf.model_preparation.gul_inputs.get_gul_input_items
RUNNING: oasislmf.model_preparation.summaries.get_exposure_totals
RUNNING: oasislmf.model_preparation.gul_inputs.write_gul_input_files
RUNNING: oasislmf.model_preparation.gul_inputs.write_items_file
RUNNING: oasislmf.model_preparation.gul_inputs.write_coverages_file
RUNNING: oasislmf.model_preparation.summaries.get_summary_mapping
RUNNING: oasislmf.model_preparation.summaries.write_mapping_file
RUNNING: oasislmf.model_preparation.il_inputs.get_il_input_items
RUNNING: oasislmf.model_preparation.il_inputs.write_il_input_files
RUNNING: oasislmf.model_preparation.il_inputs.write_fm_policytc_file
RUNNING: oasislmf.model_preparation.il_inputs.write_fm_profile_file
RUNNING: oasislmf.model_preparation.il_inputs.write_fm_programme_file
/usr/local/lib/python3.6/site-packages/oasislmf/utils/log.py:111: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  result = func(*args, **kwargs)
/usr/local/lib/python3.6/site-packages/oasislmf/model_preparation/summaries.py:868: UserWarning: "102" is not a valid OED peril ID/code. Please check the source exposure file.
  warnings.warn('"{}" is not a valid OED peril ID/code. Please check the source exposure file.'.format(peril_id))
Traceback (most recent call last):
  File "/usr/local/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/usr/local/lib/python3.6/site-packages/oasislmf/cli/root.py", line 41, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/usr/local/lib/python3.6/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/usr/local/lib/python3.6/site-packages/oasislmf/cli/model.py", line 294, in action
    group_id_cols=group_id_cols
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/log.py", line 111, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/manager.py", line 619, in generate_oasis_files
    chunksize=write_chunksize
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/log.py", line 111, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/model_preparation/il_inputs.py", line 1094, in write_il_input_files
    getattr(this_module, 'write_{}_file'.format(fn))(il_inputs_df.copy(deep=True), il_input_files[fn], chunksize)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/log.py", line 111, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/model_preparation/il_inputs.py", line 996, in write_fm_programme_file
    fm_programme_df = set_dataframe_column_dtypes(fm_programme_df, dtypes)
  File "/usr/local/lib/python3.6/site-packages/oasislmf/utils/data.py", line 1042, in set_dataframe_column_dtypes
    df = df.astype(_dtypes)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 5683, in astype
    col.astype(dtype=dtype[col_name], copy=copy, errors=errors)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 5698, in astype
    new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 582, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 442, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 625, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 868, in astype_nansafe
    raise ValueError("Cannot convert non-finite values (NA or inf) to integer")
ValueError: Cannot convert non-finite values (NA or inf) to integer
```

### Oasislmf level 2
```
ipdb> il_inputs_df[il_inputs_df['level_id'] == 2]                                                                                                                                                             
         acc_idx accnumber  agg_id  areaperil_id  attachment  bitiv  calcrule_id  condnumber  ...  polnumber  portnumber  share        tiv    tiv_sum  vulnerability_id  orig_level_id      agg_tiv
1139068      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139069      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139070      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139071      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139072      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139073      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139074      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139075      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139076      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139077      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139078      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139079      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139080      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139081      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139082      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139083      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139084      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139085      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139086      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139087      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139088      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139089      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139090      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139091      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139092      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139093      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139094      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139095      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139096      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139097      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139098      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139099      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139100      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139101      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139102      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139103      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139104      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139105      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139106      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139107      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139108      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139109      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139110      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139111      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139112      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139113      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139114      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139115      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139116      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139117      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139118      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139119      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139120      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139121      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139122      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139123      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139124      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139125      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139126      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139127      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139128      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139129      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139130      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139131      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139132      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139133      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139134      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139135      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139136      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139137      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139138      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139139      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139140      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139141      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139142      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139143      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139144      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139145      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139146      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139147      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139148      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139149      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139150      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139151      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139152      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139153      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139154      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139155      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139156      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139157      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139158      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139159      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139160      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139161      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139162      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139163      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139164      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139165      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139166      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  103000000.0
1139167      0.0         1       1         18230         0.0    0.0           34           0  ...          1           1    1.0  1000000.0  1000000.0          21110000             10  10300000
```

**Comment by benhayes21** [comment]
I think that the issue here might be due to the account file having a single row with AccNumber = 1 but the loc file has many AccNumber valuess in it - so the input files are not compatible. This should probably be handled more gracefully, but that looks to be the most likely cause to me.

**Comment by benhayes21** [comment]
Recommend we add a "rejected location" report to highlight non modeled locations
