### ISSUE TITLE
oasislmf test fm doesn't work and there is no documentation

### ISSUE THREAD

**Issue by johcarter** [OasisLMF/OasisLMF#862]
## Issue Description

oasislmf test fm -c {test case name} used to produce and compare outputs from running oasislmf exposure run with its expected folder. Now it no longer seems to work, and there is no documentation about how to use it. Need to add a section of documentation, perhaps on https://oasislmf.github.io/docs/oasis_mdk.html

## Steps to Reproduce (Bugs only)

1. go into validation and run oasislmf test fm -c insurance

## Version / Environment information

 
WSL Ubuntu-20-04 within python virtual env
latest oasislmf package

## Example data / logs

~/dev/OasisLMF_761-fm-tests/validation$ oasislmf test fm -c insurance

Stating oasislmf command - RunFmTest
RUNNING: oasislmf.manager.interface
Traceback (most recent call last):
  File "/home/joh/OasisLMF/venv3/bin/oasislmf", line 7, in <module>
    sys.exit(RootCmd().run())
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/oasislmf/cli/root.py", line 41, in run
    return super(OasisBaseCommand, self).run(args=args)
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/argparsetree/cmd.py", line 159, in run
    return cmd_cls(sub_command_name).run(args)
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/argparsetree/cmd.py", line 161, in run
    return self.action(args) or 0
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/oasislmf/cli/command.py", line 131, in action
    manager_method(**_kwargs)
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/oasislmf/utils/log.py", line 111, in wrapper
    result = func(*args, **kwargs)
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/oasislmf/manager.py", line 87, in interface
    return computation_cls(**kwargs).run()
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/oasislmf/computation/run/exposure.py", line 341, in run
    return self.execute_test_case(self.test_case_name)
  File "/home/joh/OasisLMF/venv3/lib/python3.8/site-packages/oasislmf/computation/run/exposure.py", line 380, in execute_test_case
    test_dir = os.path.join(self.test_case_dir, test_case)
  File "/usr/lib/python3.8/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by sambles** [comment]
I've taken a quick look, something odd is going on with the default paths. It looks to work if you give it the base test directory: 

```
$ oasislmf test fm --test-case-name insurance --test-case-dir validation/

Stating oasislmf command - RunFmTest
RUNNING: oasislmf.manager.interface
RUNNING: oasislmf.lookup.factory.generate_key_files
COMPLETED: oasislmf.lookup.factory.generate_key_files in 0.09s

Processing arguments - Creating Oasis Files

Generating Oasis files (GUL=True, IL=True, RIL=False)
RUNNING: oasislmf.preparation.gul_inputs.get_gul_input_items
Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
NumExpr defaulting to 8 threads.
COMPLETED: oasislmf.preparation.gul_inputs.get_gul_input_items in 0.05s
RUNNING: oasislmf.preparation.summaries.write_exposure_summary
RUNNING: oasislmf.preparation.summaries.get_exposure_summary
RUNNING: oasislmf.preparation.summaries.get_exposure_totals
  ... 
```
If the package defaults `self.test_case_dir` using  **os.getcwd()** it should work without needing a value for  `--test-case-dir`
